name: CI
on:
  push:
    branches:
      - main
      - e35
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - run: go test ./...

      - run: go install github.com/pelletier/go-toml/v2/cmd/tomll@latest

      - run: tomll bsc.toml
      - run: tomll chapel.toml

      - run: tomll webseed/bsc.toml
      - run: tomll webseed/chapel.toml

